from SetupData import setup_data
from HelpFunctions import save_properties
from IntroWindow import IntroWindow

setup_data("Strength of passport (in countries enterable without need of visa) (higher is better).csv",treat_missing_data_as_bad=True,dif=2,additional_information=True,additional_information_column_list=[2,3,4]) #explain
setup_data("Forest area in 1000 hectars (by 100 km^2) (higher is better).csv",treat_missing_data_as_bad=True,dif=1)
setup_data("Yearly average temperature in (in Celsius) (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Annual precipiation (in mm) (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Number of different established languages and dialects (higher is better).csv",treat_missing_data_as_bad=True,dif=3) #was ist eine Sprache
setup_data("First use of current flag (older is better).csv",ascending=True,dif=4)
setup_data("Gender Gap Index (more equal is better).csv",dif=2) #was ist das genau
setup_data("Prison occupacy (lower is better).csv",ascending=True,dif=4)
setup_data("Percentage of prisoners being female (higher is better).csv",treat_missing_data_as_bad=True,dif=5)
setup_data("Number of prisoners per 100,000 population (lower is better).csv",ascending=True,dif=3)
setup_data("Press Freedom Index (more free is better).csv",ascending=True,dif=2)

setup_data("Percentage of alcohol being consumed is wine (higher is better).csv",treat_missing_data_as_bad=True,dif=3) #genauer 
setup_data("Percentage of alcohol being consumed is beer (higher is better).csv",treat_missing_data_as_bad=True,dif=3) #genauer
setup_data("Alcohol consumption per person per year (lower is better) (in l).csv",ascending=True,dif=2) #liter und lower is better umdrehen
setup_data("Fishing in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Garlic production in tons  (by 10,000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Soybean production in tons (by 10,000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Tomato production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=3,cluster="productioncluster")
setup_data("Pineapple production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=3,cluster="productioncluster")
setup_data("Plum production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Grape production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Eggplant production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Cherry production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Wine production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Coffee production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=3,cluster="productioncluster")
setup_data("Cucumber production in tons (by 1000 population) (higher is better).csv",dif=4,cluster="productioncluster")
setup_data("Coconut prodcution in tons  (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Apricot production in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Barley production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Potato production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Apple production in tons (by 100 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=3,cluster="productioncluster")
setup_data("Fishing in tons (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=4,cluster="productioncluster")
setup_data("Industrial production growth rate 2017 in percent (higher is better).csv",dif=4) #erklären
setup_data("Minimum wage PPP-adjusted in Int$ (higher is better).csv",treat_missing_data_as_bad=True,dif=2) #was ist PPP
setup_data("Meat consumption in kg per year and person (lower is better).csv",dif=2,ascending=True)

setup_data("Irrigated area (by 100 km^2 country size) (higher is better).csv",treat_missing_data_as_bad=True,dif=3,cluster="productioncluster")
setup_data("Number of different breeding bird species (higher is better).csv",dif=4,cluster="number of animalcluster")
setup_data("Number of different mammal species (higher is better).csv",dif=4,cluster="number of animalcluster")
setup_data("Taxi price per 1km in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Average price for public transport in US$ (one-way-ticket) (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Average price for public transport in US$ (monthly pass) (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Percentage of people feeling safe walking alone (during the day) (higher is better).csv",dif=2)
setup_data("Percentage of people feeling safe walking alone (at night) (higher is better).csv",dif=2)

setup_data("Price of 1l of milk in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of 1kg of rice in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of a dozen eggs in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of a kg of apples in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of a skinless, boneless chicken breast in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of 1.5l water bottle in supermarket in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of 0.5l local beer in supermarket in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of one head of lettuce in supermarket in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of 1kg of tomatoes in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of 1kg of potatoes in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")

setup_data("Price of newest nike shoes in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of one pair of Levi 501s or equivalent in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price for garbage, water, heating, electricity for 85 sqm apartment in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of a regular cappuchino in a restaurant in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of a mcdonalds menu in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price for a 3 course meal for 2 in a normal restaurant in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of 0.5 l normal beer in a restaurant in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of a bottled water in a restaurant in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Price of a new Volkswagen Golf 1.4 in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Monthly price of broadband internet 6Mpbs, uncapped data in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of local 1kg cheese in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")
setup_data("Price of one pack of Marlboro in US$ (lower is better).csv",ascending=True,dif=4,cluster="pricecluster")

setup_data("Obesity rate (lower is better).csv",ascending=True,dif=2)
setup_data("Unemployment rate (lower is better).csv",ascending=True,dif=3)
setup_data("Chess grandmasters per capita (higher is better).csv",treat_missing_data_as_bad=True,dif=4)
setup_data("Number of guns per 100 inhabitants (lower is better).csv",ascending=True,dif=4)
setup_data("Roller coasters per million inhabitants (higher is better).csv",dif=4)
setup_data("Cinema ticket price in US$ (lower is better).csv",ascending=True,dif=3,cluster="pricecluster")
setup_data("Believes crime increasing in 2010-2014 (lower is better).csv",ascending=True,dif=4)
setup_data("Rapes per 100,000 population (lower is better).csv",ascending=True,dif=4)
setup_data("Gasoline prices in US$ (lower is better).csv",ascending=True,dif=2)
setup_data("Percentage of land being protected (higher is better).csv",dif=4)
setup_data("Unpaid diplomatic parking fines in NYC (lower is better).csv",ascending=True,dif=4)
setup_data("Minimum number of paid annual leave (higher is better).csv",dif=2)
setup_data("Number of paid annual public holidays (higher is better).csv",dif=2)
setup_data("Percentage of people using the internet (higher is better).csv",treat_missing_data_as_bad=True,dif=2)

setup_data("Perception of corruption score (less corrupt is higher) (higher is better).csv",dif=2) #Erklären woher das kommt
setup_data("Generosity score (higher is better).csv",dif=2) #Erklären woher das kommt
setup_data("Freedom to make life choices score (higher is better).csv",dif=2) #Erklären woher das kommt
setup_data("Healthy life expectancy score (higher is better).csv",dif=2) #Erklären woher das kommt
setup_data("Social support score (higher is better).csv",dif=2) #Erklären woher das kommt
setup_data("World Happiness Index (higher is better).csv",dif=1)
setup_data("Number of mcdonalds restaurants (by 1,000,000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Suicides per 100,000 population (lower is better).csv",ascending=True,dif=2)
setup_data("Percentage of people who are proficient in english (higher is better).csv",dif=1)
setup_data("Size of largest island in km2 (higher is better).csv",treat_missing_data_as_bad=True,dif=1)
setup_data("Number of UNESCO World Heritage Sites (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("CO2 emission in tons per capita (lower is better).csv",ascending=True,dif=1)
setup_data("Agreement to the statement religion is important (higher is better).csv",ascending=False,dif=2)
setup_data("Percentage of people being atheist (higher is better).csv",dif=1)
setup_data("Net migration rate per 1000 population (higher is better).csv",dif=2)
setup_data("Number of soldiers per 1000 population (higher is better).csv",dif=3)
setup_data("Percentage of population being christian (higher is better).csv",dif=2)
setup_data("Percentage of population being hindu (higher is better).csv",dif=1)
setup_data("Percentage of population being muslim (higher is better).csv",dif=2)
setup_data("Chinese population (by 1000 population) (higher is better).csv",dif=3)
setup_data("Number of urban areas with more than 1 mio. citizens (higher is better).csv",dif=1)
setup_data("Side of traffic (left hand side beats right hand side) (higher is better).csv",dif=1)
setup_data("Number of visits by an US-President (since formation of the country) (higher is better).csv",dif=2,treat_missing_data_as_bad=True)
setup_data("Home ownership rate (higher is better).csv",dif=2)
setup_data("Number of wiki-languages of most famous person from that country (higher is better).csv",dif=1,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous architect of that country (higher is better).csv",dif=2,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of urban areas with more than 1 mio. citizens (higher is better).csv",dif=1)
setup_data("Number of twitter followers of head of state resp. head of government (higher is better).csv",dif=1,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of models from that country with a wiki-page (by 1,000,000 population) (higher is better).csv",dif=2)
setup_data("Number of first level administrative regions (i.e. states in the US or prefectures in Japan) (higher is better).csv",dif=4)
setup_data("Number of airports (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Number of airports (by 1,000,000 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=3)
setup_data("Number of wiki-languages of head of state resp. head of government (higher is better).csv",dif=2,additional_information=True,treat_missing_data_as_bad=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous band from that country (higher is better).csv",dif=3,additional_information=True,treat_missing_data_as_bad=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous food from that country (higher is better).csv",treat_missing_data_as_bad=True,dif=1,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous actor from that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous singer of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous person from that country, who is still alive (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous touristic sight of that country (higher is better).csv",treat_missing_data_as_bad=True,dif=1,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous woman from that country (higher is better).csv",treat_missing_data_as_bad=True,dif=3,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Facebook accounts (by 10 population) (higher is better).csv",treat_missing_data_as_bad=True,dif=2)
setup_data("Prostitutes per 10,000 inhabitants (lower is better).csv",dif=3,ascending=True)
setup_data("Air cleanliness in percent (higher is better).csv",dif=3)
setup_data("Year of last executed death penalty (lower is better).csv",dif=3,ascending=True)
setup_data("Global peace index (more peaceful is better) (lower is better).csv",dif=2,ascending=True)
setup_data("Number of volcanos in that country (higher is better).csv",dif=2)
setup_data("Percentage of parliament member being female (higher is better).csv",dif=2)
setup_data("First year in which (some) women were granted (restricted) suffrage (lower is better) .csv",dif=2,ascending=True)
setup_data("Pupil-teacher ratio (lower is better).csv",dif=2,ascending=True)
setup_data("Number of wiki-languages of most famous city with at most 5000 citizens (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous city with at most 20,000 citizens (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous city with at most 100,000 citizens (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous historical person (at least 50 years dead) (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous historical person (at least 100 years dead) (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous historical person (at least 200 years dead) (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous historical person (at least 500 years dead) (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Literacy rate (higher is better).csv")
setup_data("Number of wiki-languages of most famous one-day historic event at least 90 years ago (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Highest building of that country in meter (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4],dif=3)
setup_data("Number of wiki-languages of most famous scientist of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4],treat_missing_data_as_bad=True)
setup_data("Minimum number of paid annual vacation (higher is better).csv")
setup_data("Number of wiki-languages of most famous writer of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Median age (lower is better).csv",ascending=True)
setup_data("Number of wiki-languages of most famous one-day historic event in the 21st century (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous one-day historic event at least 200 years ago (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous one-day historic event (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Size of the lower house (or equivalent) of that country (higher is better).csv")
setup_data("Person of that country with the most social media follower (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Percentage of marriages getting divorced in percent (lower is better).csv",ascending=True)
setup_data("Percentage of GDP spent on education (higher is better).csv")
setup_data("Number of wiki-languages of the capital (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Annual cannabis prevalence in percent (lower is better).csv",ascending=True)
setup_data("Drug deaths per 100,000 population (lower is better).csv",ascending=True)
setup_data("Highest mountain of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of physicians by 10,000 population (higher is better).csv")
setup_data("Average elevation (higher is better).csv")
setup_data("Number of cigarettes smoked per year per person (lower is better).csv",ascending=True)
setup_data("Oil production in barrel per day (higher is better).csv")
setup_data("Oil production in barrel per year (by 1000 population) (higher is better).csv",treat_missing_data_as_bad=True)
setup_data("Natural disaster risk in percent (lower is better).csv",ascending=True)
setup_data("Electrical power consumption per capita per year (in watts) (lower is better).csv",ascending=True)
setup_data("Number of wiki-languages of most famous soccer player (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Corporate tax in percent (lower is better).csv",ascending=True)
setup_data("Highest possible individual income tax in percent (lower is better).csv",ascending=True)
setup_data("VAT resp. GST in percent (lower is better).csv",ascending=True)
setup_data("Democracy index (higher is better).csv")
setup_data("Infant mortality (deaths in the first 5 years by 1000 births) (lower is better).csv",ascending=True)
setup_data("Number of wiki-languages of most famous fashion person of that country (higher is better).csv",additional_information=True,treat_missing_data_as_bad=True,additional_information_column_list=[2,3,4])
setup_data("Population growth rate in 2021 in percent (higher is better).csv")
setup_data("GDP per capita in PPP (higher is better).csv")
setup_data("Fragile state index (more stable is better) (lower is better).csv",ascending=True)
setup_data("Homeless population by 10,000 population (lower is better).csv",ascending=True)
setup_data("GDP growth in 2020 (higher is better).csv")
setup_data("Population density (in citizens per km^2) (higher is better).csv")
setup_data("Number of wiki-languages of most famous geographical feature of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous one-day event between 1950 and 2000 (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous city with at most 500,000 citizens (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous city with at most 1,000,000 citizens (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous (real) building of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4],)
setup_data("Number of wiki-languages of most famous architectural structure of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Percentage of urban population (higher is better).csv")
setup_data("Gini wealth index (more equal is better) (lower is better).csv",ascending=True)
setup_data("Gini income index (more equal is better) (lower is better).csv",ascending=True)
setup_data("Religious diversity score (higher is better).csv")
setup_data("Ethnic diversity score (higher is better).csv")
setup_data("Male- to female income ratio (more equal is better) (lower is better).csv",ascending=True)
setup_data("Number of international tourists arriving per year (higher is better).csv")
setup_data("Percentage of people working in the agricultural sector (higher is better).csv")
setup_data("Percentage of people working in the agricultural sector (lower is better).csv",ascending=True)
setup_data("Import and exports as percentage of gdp (higher is better).csv")
setup_data("Import and exports as percentage of gdp (lower is better).csv",ascending=True)
setup_data("Percentage of GDP being remittances of international migrants (higher is better).csv")
setup_data("Percentage of people trusting their national government (higher is better).csv")  
setup_data("Percentage of people being satsified with environment policy of government (higher is better).csv")
setup_data("Percentage of people having confidence in the judical system (higher is better).csv")
setup_data("Percentage of people having volunteered at least once (higher is better).csv") 
setup_data("Percentage of people saying that the local labour market is good (higher is better).csv")
setup_data("Percentage of people being satisfied with their health care quality (higher is better).csv")
setup_data("Percentage of people being satisfied with their standard of living (higher is better).csv")
setup_data("Percentage of people being satisfied with their education quality (higher is better).csv")
setup_data("Number of speakers of most spoken official language of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2])
setup_data("Number of wiki-languages of most famous painter of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Population of the most populated city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])    
setup_data("Population of the second most populated city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])    
setup_data("Population of the third most populated city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])    
setup_data("Sum of the three most populated cities of that country (higher is better).csv")
setup_data("Number of wiki-languages of most famous city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of second most famous city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of third most famous city of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Sum of wiki-languages of the three most famous cities of that country (higher is better).csv")
setup_data("Number of wiki-languages of most famous company which is neither an airline nor a national bank (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of mentions of that countrys name in the NYT from 2000 to 2016 (higher is better).csv")
setup_data("Number of wiki-languages of most famous airline of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Gay friendly travel index (higher is better).csv")
setup_data("Number of covid deaths per capita (lower is better).csv")
setup_data("Number of wiki-languages of most famous newspaper of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous street - avenue - boulevard of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous road - highway - motor circuit of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous bridge of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous place of worship (church,mosque,temple etc.) of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous (real) museum of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of chambers of the government (two chambers beat one chamber) (higher is better).csv")
setup_data("Drinking water quality score (higher is better).csv")
setup_data("Number of wiki-languages of most famous athlete of that country which is not a soccer player (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous criminal of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous health scientist of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous movie director of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous person from that country born after 2000 (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous social scientist humanities scholar of that country (higher is better).csv",additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous cleric of that country (higher is better).csv",additional_information=True,treat_missing_data_as_bad=True,additional_information_column_list=[2,3,4])
setup_data("Median wealth in US$ (nominal) (higher is better).csv",additional_information=False)
setup_data("Index of Economic Freedom (higher is better).csv")
setup_data("Ease of doing business index (easier is better).csv",ascending=True)
setup_data("Economic Complexity Index (more complex is better).csv")
setup_data("Percentage of GDP spent on R&D (higher is better).csv")
setup_data("Number of scientific and technical journal articles in English from that country (by 1,000,000 population) (higher is better).csv")
setup_data("Percentage of population being female (higher is better).csv")
setup_data("Percentage of population being female (lower is better).csv")
setup_data("Projected population in 2100 (higher is better).csv")
setup_data("Projected population growth until 2100 in percent (higher is better).csv")
setup_data("Estimated population growth 1950-2020 (higher is better).csv")
setup_data("Estimated population in 1950 (higher is better).csv")
setup_data("Annual HIV deaths (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual Malaria deaths (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual alcohol deaths (by 1,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by traffic related causes (by 10,000 population).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual Hepatitis deaths (by 1,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by fire and heat (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by digestive diseases (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Cirrhosis and other chronic liver diseases (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by malnutrition (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by poisonings (by 1,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by chronic kidney diseases (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Diabetes Mellitus (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by conflict and terrorism (by 10,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by neoplasms (by 1000 population) (lower is better) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by exposure to environmental cold or heat (by 1,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by exposure to force of nature (by 10,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by neonatal disorders (by 10,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by lower respiratory infections (by 10000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by cardiovascular diseases (by 1000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Tuberculosis (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by maternal disorders (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by drowning (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by nutritional deficiencies (by 100,000 population).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Parkinson's disease (by 100,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Alzheimer's disease and other dementias (by 10,000 population).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Annual deaths by Meningitis (by 1,000,000 population) (lower is better).csv",ascending=True,cluster="death_by_cause_cluster")
setup_data("Percentage of US-american citizens having a positive opinion about that country (higher is better).csv")
setup_data("Percentage of US-american citizens having heard of that country (higher is better).csv")
setup_data("Natural gas production (in million m^3 per year) (by 10,000 population) (higher is better).csv",treat_missing_data_as_bad=True)
setup_data("Books published in that country per year (by 10,000 population) (higher is better).csv")
setup_data("Annual cocaine prevalence (lower is better).csv",ascending=True)
setup_data("Annual opioid prevalence (lower is better).csv",ascending=True)
setup_data("Foreign currency reserves of that country (incl. gold and special drawing rights) (by 10,000 population) (higher is better).csv")
setup_data("Global Terrorism Index (less incidents are better) (lower is better).csv",ascending=True)
setup_data("Youth unemployment in 2021 (lower is better).csv",ascending=True)
setup_data("Year of first KFC opening in that country (lower is better).csv",ascending=True)
setup_data("Year of first Burger King opening in that country (lower is better).csv",ascending=True)
setup_data("Inflation rate in 2021 (lower is better).csv",ascending=True)
setup_data("Average import duty in % (lower is better).csv",ascending=True)
setup_data("Average inflation rate 2017-2021 (lower is better).csv",ascending=True)
setup_data("S&P credit rating (better rating is better) (lower is better).csv",ascending=True,additional_information=True,additional_information_column_list=[2])
setup_data("Amount of currencies one US$ can buy (higher is better).csv",additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Export to import ratio (higher is better).csv")
setup_data("Number of characters of official name of that country (higher is better).csv",additional_information=True)
setup_data("Refugee population (by 100,000 population) (higher is better).csv")
setup_data("Number of emigrants from that country (by 1,000 population) (higher is better).csv")
setup_data("Percentage of population being immigrants (higher is better).csv")
setup_data("Female labor force participation rate (higher is better).csv")
setup_data("Male labor force participation rate (higher is better).csv")
setup_data("Labor force participation rate (higher is better).csv")
setup_data("Fertilizer use (lower is better).csv",ascending=True)
setup_data("Shadow economy (lower is better).csv",ascending=True)
setup_data("Road Quality Index (higher is better).csv",ascending=True)
setup_data("Percentage of total stock market capitalization to GDP (higher is better).csv",)
setup_data("Percentage of people being fully vaccinated against Covid (higher is better).csv",)
setup_data("Maternal deaths by 100,000 births (lower is better).csv",ascending=True)
setup_data("Neonatal deaths by 1000 births (lower is better).csv",ascending=True)
setup_data("Percentage of people having a credit card (higher is better).csv",)
setup_data("Share of clean energy (higher is better).csv",)
setup_data("Number of different taxes (lower is better).csv",ascending=True)
setup_data("Government debt as percentage of GDP (lower is better).csv",ascending=True)
setup_data("Income from natural resources as percent of GDP (lower is better).csv",ascending=True)
setup_data("Number of tanks (by 10,000,000 population) (higher is better).csv",treat_missing_data_as_bad=True)
setup_data("Number of military ships (by 100,000,000 population) (higher is better).csv",treat_missing_data_as_bad=True)
setup_data("Number of military aricrafts (by 10,000,000 population) (higher is better).csv",treat_missing_data_as_bad=True)
setup_data("National Holiday (earlier in the year is better).csv",ascending=True,additional_information=True,additional_information_column_list=[2,3,4])
setup_data("Number of wiki-languages of most famous desert of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous airport of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous national park - garden - zoo in that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 50 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 100 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 200 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 500 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 500 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 500 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous historical woman (at least 500 years dead) of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous female scientist of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous female athlete of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous female actor of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous battle which took place in that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous woman being born after 2000 (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of wiki-languages of most famous female singer of that country (higher is better).csv",dif=2,treat_missing_data_as_bad=True,additional_information=True,additional_information_column_list=[2,7,8])
setup_data("Number of mobile phone lines (by 100 population) (higher is better).csv")
setup_data("Country size (higher is better).csv",is_end_only=True)
setup_data("Population (higher is better).csv",is_end_only=True)
setup_data("Latitude of northernmost point of that country (northern is better) (higher is better).csv",is_end_only=True)
setup_data("Latitude of southernmost point of that country (southern is better) (lower is better).csv",is_end_only=True)

# save_properties()
# print(clusterdict.keys())



if __name__ == '__main__':
    IntroWindow()



# propertydict=dict()
# for country in allCountries:
#     propertydict[country.name]=country.dictofattributes

# with open("backenddata/attributedict","wb") as f:
#     pickle.dump(propertydict,f)
# print("success")

# root=tk.Tk()
# MainWindow(bild=im,main=root)
# root.mainloop()

# for i in range (100):
#     try:
#         for j in range (100):
#             try:
#                 finaldatalist.append(data[i]["data"][j])
#             except:
#                 break
#     except:
#         break

# df=pd.DataFrame(finaldatalist)
# print(df)