from __future__ import annotations
from typing import TYPE_CHECKING

import pandas as pd
import pickle

import alternative_names
import categoryname_to_displayed_name

if TYPE_CHECKING:
    from country import Country
    from player import Player
    from category import Category

resize_ratio = [3500 / 14063, 1737 / 6981]

oceanblue = (44, 130, 201)
yellow = (255, 255, 0)
grey = (128, 128, 128)
purple = (128, 0, 128)
orange = (255, 128, 0)
red = (255, 0, 0)
green = (0, 255, 0)
white = (255, 255, 255)
realgrey = (105, 105, 105)
gold = (255, 215, 0)

country_name_list : list[str] = []
# flagframedict = dict()
all_countries_available : list[Country] = []
# clusterdict = dict()
clusternamelist = []
all_players: dict[str,Player] = dict()

all_countries_in_game : list[Country] = []
all_categories : list[Category] = []
all_categories_names_and_clusters : list[str] = []

mycounter = 0
# whichcountrydict = dict()

p = pd.read_csv("data/important/countrylist.csv",
                index_col=False,
                keep_default_na=False)
countries_for_language_en = p.values.tolist()

neighboring_countries : pd.DataFrame = pd.read_csv("data/important/country_borders.csv")
neighboring_countries.columns = list(range(len(neighboring_countries.columns))
)
reverse_countries_alternative_names : dict[str,str] = dict()


category_to_displayed_name_dict : dict[str,str] = categoryname_to_displayed_name.category_name_to_displayed_name_dict
category_to_displayed_guess_hint : dict[str,str] = categoryname_to_displayed_name.category_name_to_displayed_guess_hint
category_to_displayed_extra_information_category : dict[str,str] = categoryname_to_displayed_name.category_name_to_displayed_extra_information_category

countries_alternative_names = alternative_names.countries_alternative_names

for item in countries_alternative_names.keys():
    countries_alternative_names[item].append(item)

for mlist in countries_alternative_names.values():
    for key in countries_alternative_names.keys():
        if countries_alternative_names[key] == mlist:
            for item in mlist:
                reverse_countries_alternative_names[item.lower()] = key
                reverse_countries_alternative_names[item] = key

for item in countries_for_language_en:
    reverse_countries_alternative_names[item[1].lower()] = item[1]

for item in countries_for_language_en:
    reverse_countries_alternative_names[item[1]] = item[1]


with open("backenddata/propertydict_new", "rb") as handle:
    my_property_dict = pickle.load(handle)


# a dictionary which takes a string and if it is a clustername
# returns the list of categories associated to it. If it is just a normal
# categoryname it returns a list with only the asked category in it.
dictionary_attribute_name_to_attribute : dict[str,list[Category]] = {}


countrynames_to_ignore_because_not_in_game: list[str] = [
    "African countries",
    "French Polynesia, New Caledonia, Wallis and Futuna",
    "Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines",
    "Bonaire, Sint Eustatius and Saba",
    "Australia / New Zealand",
    "OCEANIA",
    "No income group available",
    "Western Asia",
    "NORTHERN AMERICA",
    "Northern America",
    "Western Europe",
    "Northern Europe",
    "EUROPE AND NORTHERN AMERICA",
    "EUROPE",
    "Southern Europe",
    "Polynesia",
    "NORTHERN AFRICA AND WESTERN ASIA",
    "Central Asia",
    "Eastern Europe",
    "Southern Africa",
    "WORLD",
    "Caribbean",
    "South America",
    "Middle Africa",
    "SUB-SAHARAN AFRICA",
    "Western Africa",
    "Eastern Africa",
    "LATIN AMERICA AND THE CARIBBEAN",
    "South-Eastern Asia",
    "Middle-income countries",
    "Northern Africa",
    "Melanesia",
    "Central America",
    "CENTRAL AND SOUTHERN ASIA",
    "EASTERN AND SOUTH-EASTERN ASIA",
    "Southern Asia",
    "Eastern Asia",
    "Faroe Isl.",
    "Euro area",
    "Northern Mariana Islands (United States)",
    "Republika Srpska (Bosnia and Herzegovina)",
    "German Empire",
    "Kosovo (Disputed)",
    "Federation of Bosnia and Herzegovina (Bosnia and Herzegovina)",
    "Wales (United Kingdom)",
    "Northern Ireland (United Kingdom)",
    "Aruba (Kingdom of the Netherlands)",
    "Kurdistan (Iraq)",
    "United States Virgin Islands (United States)",
    "Florida (United States)",
    "American Samoa (United States)",
    "Minas Gerais (Brazil)",
    "Aragon (Spain)",
    "England (United Kingdom)",
    "Mayotte (France)",
    "Sardinia (Italy)",
    "Brussels-Capital Region (Belgium)",
    "Guernsey (British Islands)",
    "Herm (British Islands)",
    "Jersey (British Islands)",
    "Sark (British Islands)",
    "Somaliland (Disputed)",
    "Martinique (France)",
    "Bermuda (United Kingdom)",
    "British Empire",
    "Guadeloupe (France)",
    "Azores (Portugal)",
    "Anguilla (United Kingdom)",
    "Norfolk Island (Australia)",
    "Ascension (United Kingdom)",
    "French Guiana (France)",
    "Montserrat (United Kingdom)",
    "Pitcairn Islands (United Kingdom)",
    "Saint Helena (United Kingdom)",
    "South Georgia and the South Sandwich Islands (United Kingdom)",
    "Tristan da Cunha (United Kingdom)",
    "Falkland Islands (United Kingdom)",
    "Greenland (Denmark)",
    "Québec (Canada)",
    "French Polynesia (France)",
    "British Virgin Islands (United Kingdom)",
    "Madeira (Portugal)",
    "Curaçao (Kingdom of the Netherlands)",
    "Cayman Islands (United Kingdom)",
    "Isle of Man (British Islands)",
    "São Paulo (Brazil)",
    "Flanders (Belgium)",
    "Guam (United States)",
    "Sarawak (Malaysia)",
    "Puerto Rico (United States)",
    "Faroe Islands (Denmark)",
    "Acadia (Canada)",
    "Tatarstan (Russia)",
    "Turks and Caicos Islands (United Kingdom)",
    "Sabah (Malaysia)",
    "Gibraltar (United Kingdom)",
    "Catalonia (Spain)",
    "Wallonia (Belgium)",
    "Rio Grande do Sul (Brazil)",
    "French Community (Belgium)",
    "East Germany",
    "Sint Maarten (Kingdom of the Netherlands)",
    "German-speaking Community (Belgium)",
    "Scotland (United Kingdom)",
    "Saba (Kingdom of the Netherlands)",
    "Alderney (British Islands)",
    "Réunion (France)",
    "Falkland Islands (Islas Malvinas)",
    "Gambia, The",
    "Bahamas, The",
    "New Caledonia (France)",
    "Abkhazia",
    "French Southern Territories (France)",
    "United States Minor Outlying Islands",
    "South Ossetia",
    "Artsakh",
    "Bir Tawil (terra nullius)",
    "Åland (Finland)",
    "Isle of Man (British Crown Dependency)",
    "Curaçao (Netherlands)",
    "Heard Island and McDonald Islands (Australia)",
    "Jan Mayen (Norway)",
    "U.S. Virgin Islands (United States)",
    "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)",
    "Bonaire (Netherlands)",
    "Akrotiri and Dhekelia (United Kingdom)",
    "Aruba (Netherlands)",
    "Easter Island (Chile)",
    "Christmas Island (Australia)",
    "Jersey (British Crown Dependency)",
    "Guernsey (British Crown Dependency)",
    "British Indian Ocean Territory (United Kingdom)",
    "Bouvet Island (Norway)",
    "Sint Maarten (Netherlands)",
    "Saint Barthélemy (France)",
    "Sint Eustatius (Netherlands)",
    "Cocos (Keeling) Islands (Australia)",
    "Saba (Netherlands)",
    "Tokelau (New Zealand)",
    "Clipperton Island (France)",
    "Ashmore and Cartier Islands (Australia)",
    "Kosovo [1]",
    "South Georgia (United Kingdom)",
    "French Southern and Antarctic Lands (Except Antarctica)",
    "France (Metropolitan France)",
    "Netherlands (European Netherlands)",
    "Wales",
    "Antarctic Circle",
    "Tropic of Capricorn",
    "Equator",
    "Tropic of Cancer"
] + [
    'Monaco', 'Liechtenstein', 'San Marino', 'Andorra', 
                    'Vatican', 'Cook Islands', 'Nauru', 'Niue', 'Palau', 'Tuvalu', 'Northern Mariana Islands',
                    'Guam', 'Kiribati', 'Micronesia', '', 'Marshall Islands', 'Tonga', 'Samoa', 'Solomon Islands',
] + [
    "Barbados",
    "Saint Kitts and Nevis",
    "Vatican City",
    "Seychelles",
    "Saint Vincent and the Grenadines",
    "Antigua and Barbuda",
    "Saint Lucia",
    "Grenada",
    "Dominica",
    "Vanuatu",
    "Sao Tome & Principe",
    "South Sudan",
    "Kosovo",
    "American Samoa",
    "Puerto Rico",
    "Cayman Islands",
    "New Caledonia",
    "Bermuda",
    "French Guiana",
    "French Polynesia",
    "Caribbean Netherlands",
    "Curaçao",
    "Aruba",
    "Sint Maarten",
    "Aland Islands",
    "Greenland",
    "Guadeloupe",
    "Guernsey",
    "Jersey",
    "Martinique",
    "Mayotte",
    "Reunion",
    "Saint Barthelemy",
    "Saint Martin",
    "U.S. Virgin Islands",
    "Wallis and Futuna",
    "Western Sahara",
    "Anguilla",
    "British Virgin Islands",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Faroe Islands",
    "Gibraltar",
    "Isle of Man",
    "Montserrat",
    "Norfolk Island",
    "Pitcairn",
    "Tokelau",
    "Turks and Caicos Islands",
    "British Indian Ocean Territory",
    "Falkland Islands",
    "Saint Helena",
    "Saint Pierre and Miquelon",
    "Republika Srpska",
    "Northern Ireland・Eｯ [Note]",
    "Trinidad and Tobago・Eｯ",
    "Scotland [Note]",
    "Kosovo・Eｯ",
    "Saint Lucia・Eｯ",
    "Saint Kitts and Nevis・Eｯ",
    "Somaliland",
    "Crimea",
    "French Southern Territories",
    "Heard & McDonald Islands",
    "Bouvet Island",
    "Antigua & Barbuda",
    "Antarctica",
    "Oland Islands",
    "Pitcairn Islands",
    "South Georgia & South Sandwich Islands",
    "St. Lucia",
    "St. Martin",
    "Svalbard & Jan Mayen",
    "St. Pierre & Miquelon",
    "St. Vincent & Grenadines",
    "St. Barthelemy",
    "St. Helena",
    "St. Kitts & Nevis",
    "U.S. Outlying Islands",
    "Turks & Caicos Islands",
    "Wallis & Futuna",
    "Cﾃｴte d・・Ivoire",
    "ﾃ・land Islands",
    "São Tomé & Príncipe",
    "Åland Islands",
    "Réunion",
    "St. Barthélemy",
    "West Bank",
    "Gaza Strip",
    "European Union",
    "Kosovo (2016)",
    "Netherlands Antilles",
    "FR Yugoslavia",
    "Emerging markets average",
    "Former Spanish colonies average",
    "Group of 7 countries (G7) average",
    "Religious countries average",
    "Non-religious countries average",
    "South Asia average",
    "Former Soviet republics average",
    "Cold countries average",
    "South and Central Asia average",
    "High income OECD countries average",
    "NATO countries average",
    "European Union average",
    "Eurozone average",
    "Muslim countries average",
    "OPEC countries average",
    "failed states average",
    "Former French colonies average",
    "South Georgia and the South Sandwich Islands",
    "Virgin Islands, U.S.",
    "Cocos (Keeling) Island",
    "Falkland Island (Malvinas)",
    "Svalbard and Jan Mayen",
    "Heard Islands and McDonald Islands",
    "Virgin Islands",
    "Number of different fish species (higher is better).csv",
    " U.S.",
    "Repubblic of Congo",
    "Middle Eastern and North Africa average",
    "EU",
    "England",
    "Holy See",
    "England & ﾂWales",
    "Scotland",
    "Northern Ireland",
    "Puntland",
    "Channel Islands",
    "Northern Cyprus",
    "Faeroe Islands",
    "Adoption of child under 16",
    "Birth of child (for father only)",
    "Saint Helena, Ascension and Tristan da Cunha",
    "North Cyprus",
    "Eastern Mediterranean",
    "Western Pacific",
    "Americas",
    "Global",
    "South-East Asia",
    "Europe",
    "Africa",
    "World",
    "Netherlands Antilles (ﾂNetherlands)",
    "Saint Pierre and Miquelon (ﾂFrance)",
    "(less Transboundary Sites)",
    "Jerusalem (Site proposed by Jordan)",
    "-1",
    "Turks and Caicos Islands (UK)",
    "Saint Helena, Ascension and Tristan da Cunha (UK)",
    "Wallis and Futuna (France)",
    "Saint Pierre and Miquelon (France)",
    "Latin America and the Caribbean",
    "North America",
    "Oceania",
    "Total",
    "Asia",
    "Middle East-North Africa",
    "United States Virgin Islands",
    "Cocos  Islands",
    "West Germany",
    "Soviet Union",
    "South Vietnam",
    "Yugoslavia",
    "NewfoundlandNewfoundland",
    "Czechoslovakia",
    "Saint MartinSaint Martin",
    "French West Africa",
    "British Leeward Islands",
    "Country or territory",
    "Sourceﾂ[41]",
    "Weimar Republic",
    "Spratly Islands",
    "French Southern and Antarctic Lands",
    "Svalbard",
    "Wake Island",
    "Paracel Islands",
    "Jan Mayen",
    "Akrotiri",
    "Coratia",
    "Crown of Aragon",
    "Romanian Old Kingdom",
    "-",
    "nan",
    "Transnistria",
    "Republic of Artsakh",
    "Saint Barthelemy (France)",
    "Saint Martin (France)",
    "Svalbard (Norway)",
    "Saint Helena (UK)",
    "South Georgia and the South Sandwich Islands (UK)",
    "Federated States of Micronesia",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "St. Vincent and the Grenadines",
    "Korea",
    "St. Kitts and Nevis",
    "England and ﾂWales",
    "Northern Ireland (UK)",
    "Solomon Isl.",
    "Saint Vincent",
    "Antigua-Bar.",
    "Trinidad And Tobago",
    "Saint Vincent And The Grenadines",
    "Sao Tome And Principe",
    "Antigua And Barbuda",
    "Saint Kitts And Nevis",
    "Isle Of Man",
    "Turks And Caicos Islands",
    "Wallis And Futuna",
    "Saint Pierre And Miquelon",
    "Man, Isle of",
    "Holy See (Vatican City State)",
    "Falkland Islands (Malvinas)",
    "Cocos (keeling) Islands",
    "Cyprus (North)",
    "Micronesia, Federated States of",
    "Norfolk Islands",
    "Virgin Islands, British",
    "Zanzibar",
    "Europe and Central Asia",
    "Latin America and Caribbean",
    "High income",
    "Low income",
    "Sub-Saharan Africa",
    "Upper middle income",
    "Low and middle income",
    "Timor",
    "Middle income",
    "East Asia and Pacific",
    "Micronesia (country)",
    "Lower middle income",
    "South Asia",
    "Middle East and North Africa",
    "Less developed regions",
    "Less developed regions, excluding China",
    "Less developed regions, excluding least developed countries",
    "Lower-middle-income countries",
    "Asia (UN)",
    "Africa (UN)",
    "Least developed countries",
    "Low-income countries",
    "Upper-middle-income countries",
    "Land-locked Developing Countries (LLDC)",
    "High-income countries",
    "More developed regions",
    "Latin America and the Caribbean (UN)",
    "Europe (UN)",
    "Northern America (UN)",
    "Small Island Developing States (SIDS)",
    "Oceania (UN)",
    "Saint Martin (French part)",
    "Bonaire Sint Eustatius and Saba",
    "Sint Maarten (Dutch part)",
    "Saint Barthlemy",
    "West Bank and Gaza",
    "Ant.& Barb.",
    "St. Vincent & ...",
    "S.T.&Principe",
    "N. Caledonia",
    "Bonaire"
]